"""Initial migration

Revision ID: 63b06f3df46a
Revises: 
Create Date: 2026-05-27 13:47:20.670770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b06f3df46a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_number', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=True),
    sa.Column('vehicle_category', sa.String(), nullable=True),
    sa.Column('vehicle_price', sa.String(), nullable=True),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('base_policy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('policy_number')
    )
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('accident_area', sa.String(), nullable=True),
    sa.Column('witness_present', sa.String(), nullable=True),
    sa.Column('police_report_filed', sa.String(), nullable=True),
    sa.Column('cv_damage_type', sa.String(), nullable=True),
    sa.Column('cv_damage_pct', sa.Float(), nullable=True),
    sa.Column('estimated_payout', sa.Float(), nullable=True),
    sa.Column('deductible', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fraud_found', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['policy_number'], ['policies.policy_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
